# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'ga-connect'
    userRepository: 'losper/passoa'
    defaultVersionType: 'latest'
    itemPattern: 'passoa-*'
    downloadPath: './'

- script: |
    npm install
    npm run pm-android
    npm run android
  displayName: 'npm install and build'

- script: |
   7z x passoa*.zip -r -o./ -y
   cp android/* dist/ -rf
   mv node_modules/@passoa/ dist/node_modules/@passoa/ -rf
   mv dist/node_modules/@passoa/img/libturbojpeg.so dist/
   ls dist
  displayName: 'install passoa'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/remote-android-$(Build.SourceBranchName).7z'
    replaceExistingArchive: true
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
    rm dist -rf
    npm run pm-arm
    npm run arm
  displayName: 'npm install and build'

- script: |
   7z x passoa*.zip -r -o./ -y
   cp arm/* dist/ -rf
   mv node_modules/@passoa/ dist/node_modules/@passoa/ -rf
   mv dist/node_modules/@passoa/img/libturbojpeg.so dist/
   ls dist
  displayName: 'install passoa'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/remote-arm-$(Build.SourceBranchName).7z'
    replaceExistingArchive: true
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'ga-connect'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    releaseNotesFile: 'ChangeLog'
    addChangeLog: false
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))